[profile.default]
src = "src"
out = "out"
test = "test"
libs = ["lib"]
solc = "0.8.20"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
evm_version = 'paris'
remappings = [
    "@chainlink/contracts/=lib/chainlink/contracts",
    '@chainlink/contracts-ccip/=lib/ccip/contracts/',
    '@chainlink/contracts-ccip=lib/ccip/contracts',
    '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    '@chainlink/local/=lib/chainlink-local/',
]
[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
arbitrumSepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
ethereumSepolia = "${ETHEREUM_SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
